confluence:
  url: https://confluence.hycom.pl
  api:
    url: /rest/api
    content:
      url: /content
  auth:
    pat: <personal_access_token>
  blog:
    space: <space_key>
notion:
  auth:
    iat: <integration_access_token> # integration access token
  database:
    id: <database_id>
issue:
  file: issue.txt
