confluence:
  url: https://<confluence_address>
  api:
    url: /rest/api
    content:
      url: /content
  auth:
    token: <personal_access_token>
  blog:
    space: <space_key>
medium:
  api:
    userid: <user_id>
    url: https://api.medium.com/v1/users/{}/posts
  auth:
    token: <access_token>
notion:
  auth:
    token: <integration_access_token>
  database:
    id: <database_id>
issue:
  number:
    file: issue.txt
