version: 1
formatters:
  simple:
    format: '%(asctime)s - %(levelname)s - %(name)s: %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  default:
    format: '%(asctime)s %(levelname)-8s %(name)-15s %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: default
    stream: ext://sys.stdout
  # file:
  #   class: logging.handlers.RotatingFileHandler
  #   level: DEBUG
  #   formatter: default
  #   filename: publisher.log
  #   maxBytes: 1048576 # KB
  #   backupCount: 3
loggers:
  # fileLogger:
  #   level: DEBUG
  #   handlers: [file]
  lib:
    level: DEBUG
    # handlers: [console, file]
root:
  level: DEBUG
  handlers: [console]
